version: 2.1

orbs:
  go: circleci/go@1.7.1
  docker: circleci/docker@2.0.3
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.37-alpine
    steps:
      - checkout
      - run: golangci-lint run
    environment:
      GO111MODULE: "off"
  build-and-push:
    parameters:
      user:
        description: Name of github user environment variable
        default: GHCR_USER
        type: env_var_name
      token:
        description: Name of github token environment variable
        default: GHCR_PAT
        type: env_var_name
    environment:
      DOCKER_IMAGE: ghcr.io/ntheanh201/udacity-capstone
      DOCKER_TAG: latest
    executor: docker/docker

    steps:
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - checkout
      - run:
          name: GHCR Login
          command: |
            echo "${<< parameters.token >>}" \
              | docker login ghcr.io -u "${<< parameters.user >>}" --password-stdin
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          name: Push Image
          command: |
            docker push $DOCKER_IMAGE:$DOCKER_TAG
workflows:
  build:
    jobs:
      - lint
      - build-and-push:
          requires:
            - lint
          context:
            - udacity_aws
          filters:
            branches:
              only:
                - master